const TYPE_ACTION = {
   HIDE_SPLASH: "HIDE_SPLASH",
   SHOW_LOADING: "SHOW_LOADING",
   HIDE_LOADING: "HIDE_LOADING",
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOG_OUT: "LOG_OUT",
   GET_USER_BY_ID: "GET_USER_BY_ID",
   EDIT_INFOR_USER_SUCCESSED: "EDIT_INFOR_USER_SUCCESSED",
   SHOW_LOADING: "SHOW_LOADING",
   HIDE_LOADING: "HIDE_LOADING",
   GET_RESULT_TEST: "GET_RESULT_TEST",
   GET_FORM_TEST: "GET_FORM_TEST",
   GET_LIST_DOCTOR: 'GET_LIST_DOCTOR',
   GET_LIST_HOSPITAL: 'GET_LIST_HOSPITAL',
   POST_TEST_UP_HISTORY: 'POST_TEST_UP_HISTORY',
   GET_LIST_TEST_HISTORY: 'GET_LIST_TEST_HISTORY',
   GET_LIST_HISTORY_DETAIL: 'GET_LIST_HISTORY_DETAIL'
}

export default TYPE_ACTION