const TYPE_ACTION = {
   HIDE_SPLASH: "HIDE_SPLASH",
   SHOW_LOADING: "SHOW_LOADING",
   HIDE_LOADING: "HIDE_LOADING",
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOG_OUT: "LOG_OUT",
   GET_USER_BY_ID: "GET_USER_BY_ID",
   EDIT_INFOR_USER_SUCCESSED: "EDIT_INFOR_USER_SUCCESSED",
   SHOW_LOADING: "SHOW_LOADING",
   HIDE_LOADING: "HIDE_LOADING"
}

export default TYPE_ACTION