const TYPE_ACTION = {
   HIDE_SPLASH: "HIDE_SPLASH",
   SHOW_LOADING: "SHOW_LOADING",
   HIDE_LOADING: "HIDE_LOADING",
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOG_OUT: "LOG_OUT"
}

export default TYPE_ACTION